//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_final.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ahorros_prestamosEntities : DbContext
    {
        public ahorros_prestamosEntities()
            : base("name=ahorros_prestamosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Fiadores> Fiadores { get; set; }
        public virtual DbSet<inversiones> inversiones { get; set; }
        public virtual DbSet<Inversionistas> Inversionistas { get; set; }
        public virtual DbSet<Prestamos> Prestamos { get; set; }
        public virtual DbSet<Prestatarios> Prestatarios { get; set; }
        public virtual DbSet<clientes> clientes { get; set; }
    }
}
