//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_final.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class inversiones
    {
        public int id { get; set; }
        public string tipo_inversion { get; set; }
        public string fecha_inicio { get; set; }
        public string fecha_termino { get; set; }
        public int monto_invertido { get; set; }
        public int tasa_interes { get; set; }
        public int id_garanatia { get; set; }
        public int id_comprobante { get; set; }
        public string tipo_pago { get; set; }
    }
}
