//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_final.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prestamos
    {
        public int codigo_prestamo { get; set; }
        public string fecha_solicitud { get; set; }
        public string fecha_aprobacion { get; set; }
        public string fecha_inicio { get; set; }
        public string fecha_termino { get; set; }
        public Nullable<int> monto_prestamo { get; set; }
        public Nullable<int> tasa_interes { get; set; }
    }
}
